### PR TITLE
Finished with review list and half way done with adding a review

### PR DESCRIPTION
**Pull request by aaronyabut**

### CODE REVIEW

**Comment by aaronyabut** [comment]
@spottyzot @simingyum @quargsgreene

**Review by spottyzot — CHANGES_REQUESTED** [review]
conflict @ main.js, probably just needs a pull from most recent and should work

**Comment by aaronyabut** [comment]
Oh wait maybe because I removed mines? Or am I missing something lol. I'll pull and resend another PR in a bit tho. @spottyzot

**Review by simingyum — APPROVED** [review]
Looks good

**Review by spottyzot — APPROVED** [review]

**Pull request merged**
